### ISSUE TITLE
material syntax coloring

### ISSUE THREAD

**Issue by kinghat** [lucafluri/vscode-dark-lemon-theme#1]
can you make an accompanying theme with the package that has the material syntax coloring from: https://github.com/vangware/dark-plus-material? i like that syntax coloring but also i dont think the coloring of the material icons really go with the atom syntax coloring.

**Comment by lucafluri** [comment]
I look into that

**Comment by lucafluri** [comment]
https://marketplace.visualstudio.com/items?itemName=lucafluri.dark-lemon-material

**Comment by kinghat** [comment]
> https://marketplace.visualstudio.com/items?itemName=lucafluri.dark-lemon-material

very sexy. ty! from an extension makers perspective is it better to package theme variants as one or release them individually?

**Comment by lucafluri** [comment]
For me its just personal preference
